# Generated by Django 5.0 on 2024-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GenomeTag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="userPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view", "Can view annotation"),
                    ("annotate", "Can annotate sequences"),
                    ("review", "Can review sequences"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
