# Generated by Django 5.0 on 2024-01-25 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GenomeTag", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpermission",
            options={
                "default_permissions": (),
                "permissions": [
                    ("view", "Can view annotation"),
                    ("annotate", "Can annotate sequences"),
                    ("review", "Can review sequences"),
                ],
            },
        ),
    ]
