# Generated by Django 4.2.7 on 2024-01-22 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GenomeTag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('possition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenomeTag.position')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='tags',
            field=models.ManyToManyField(to='GenomeTag.tag'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='tags',
            field=models.ManyToManyField(to='GenomeTag.tag'),
        ),
    ]
