# Generated by Django 5.0 on 2024-02-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GenomeTag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genome",
            name="annotable",
            field=models.BooleanField(default=True),
        ),
    ]
