# Generated by Django 5.0 on 2024-01-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenomeTag', '0002_tag_annotation_tags_peptide_tags_to_annotate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='to_annotate',
            new_name='Attribution',
        ),
    ]
