# Generated by Django 5.0 on 2024-02-15 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GenomeTag", "0002_genome_annotable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Closed", models.BooleanField(default=False)),
                ("creation_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "Creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("Content", models.TextField(max_length=250)),
                ("likes", models.IntegerField(default=0)),
                (
                    "Author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "Topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="GenomeTag.topic"
                    ),
                ),
            ],
        ),
    ]
