# Generated by Django 5.0 on 2024-01-26 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GenomeTag", "0002_alter_userpermission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="commentary",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="genome",
            name="DOI",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="genome",
            name="commentary",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="genome",
            name="species",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="peptide",
            name="commentary",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
