# Generated by Django 5.0 on 2024-02-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GenomeTag", "0002_genome_annotable"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
