# Generated by Django 5.0 on 2024-02-15 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GenomeTag", "0004_message_posted_date_alter_message_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="likes",
        ),
        migrations.AddField(
            model_name="message",
            name="likes",
            field=models.ManyToManyField(related_name="liked", to=settings.AUTH_USER_MODEL),
        ),
    ]
