# Generated by Django 5.0 on 2024-02-15 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GenomeTag", "0003_mailbox_read"),
        ("GenomeTag", "0005_remove_message_likes_message_likes"),
    ]

    operations = []
